ARG GO_BUILD_IMAGE
ARG ALPINE_IMAGE
FROM ${GO_BUILD_IMAGE} AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/control ./cmd/control && \
    CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/payment ./cmd/payment

FROM ${ALPINE_IMAGE}
COPY --from=build /out/control /out/payment /usr/local/bin/
