import AuthorityContinuity.Trace
import AuthorityContinuity.TopologyExamples
import AuthorityContinuity.PlanTokenStrengthening
import AuthorityContinuity.TokenWeightedAccounting

/-!
# Frozen theorem audit

Elaboration of this module confirms the complete paper-facing theorem matrix;
the commands below expose every kernel dependency in the audit log.
-/

namespace AuthorityContinuity

#check checkAC_sound
#print axioms checkAC_sound

#check guardClosure_iff
#print axioms guardClosure_iff

#check simulation_preserves_ac
#print axioms simulation_preserves_ac

#check restriction_preserves_wf_ac
#print axioms restriction_preserves_wf_ac

#check prepare_preserves_wf_ac
#print axioms prepare_preserves_wf_ac

#check ticket_step_preserves_wf_ac
#print axioms ticket_step_preserves_wf_ac

#check LifecycleState.restrictLifecycle_epoch_exact
#print axioms LifecycleState.restrictLifecycle_epoch_exact

#check canonicalProjection_zero
#print axioms canonicalProjection_zero

#check canonicalProjection_mono
#print axioms canonicalProjection_mono

#check Transfer.checkTransfer_sound
#print axioms Transfer.checkTransfer_sound

#check Transfer.topology_fiber_conservation
#print axioms Transfer.topology_fiber_conservation

#check choiceFork_allowed_iff
#print axioms choiceFork_allowed_iff

#check parallelFork_allowed_iff
#print axioms parallelFork_allowed_iff

#check replaceRestore_allowed_iff
#print axioms replaceRestore_allowed_iff

#check liveRestore_allowed_iff
#print axioms liveRestore_allowed_iff

#check choiceFork_preserves_wf_ac
#print axioms choiceFork_preserves_wf_ac

#check parallelFork_preserves_wf_ac
#print axioms parallelFork_preserves_wf_ac

#check replaceRestore_preserves_wf_ac
#print axioms replaceRestore_preserves_wf_ac

#check liveRestore_preserves_wf_ac
#print axioms liveRestore_preserves_wf_ac

#check MergeCheck.checkMergeStructure_sound
#print axioms MergeCheck.checkMergeStructure_sound

#check simulation_merge_preserves_wf_ac
#print axioms simulation_merge_preserves_wf_ac

#check direct_merge_preserves_wf_ac
#print axioms direct_merge_preserves_wf_ac

#check step_preserves_wf_ac
#print axioms step_preserves_wf_ac

#check step_attempt_safe
#print axioms step_attempt_safe

#check step_preserves_existing_binding
#print axioms step_preserves_existing_binding

#check trace_preserves_existing_binding
#print axioms trace_preserves_existing_binding

#check trace_preserves_wf_ac
#print axioms trace_preserves_wf_ac

#check trace_terminal_mono
#print axioms trace_terminal_mono

#check trace_epoch_mono
#print axioms trace_epoch_mono

#check SimulatedTrace.attempt_binding_final
#print axioms SimulatedTrace.attempt_binding_final

#check effect_coverage
#print axioms effect_coverage

#check concrete_trace_authority_safety
#print axioms concrete_trace_authority_safety

#check TopologyExamples.fresh_fragment_parallel_preflight
#print axioms TopologyExamples.fresh_fragment_parallel_preflight

/-! Source-derived token transport and within-plan-epoch accounting. -/

#check PlanTokenLinearity.TokenState.checkLinear_sound
#print axioms PlanTokenLinearity.TokenState.checkLinear_sound

#check PlanTokenLinearity.TokenState.LinearValid.token_trichotomy
#print axioms PlanTokenLinearity.TokenState.LinearValid.token_trichotomy

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete

#check PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.bound_durable_origin_afterTransfer
#print axioms PlanTokenStrengthening.bound_durable_origin_afterTransfer

#check PlanTokenStrengthening.afterTransfer_preserves_linearity_source
#print axioms PlanTokenStrengthening.afterTransfer_preserves_linearity_source

#check PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkedCanonicalDefended_token_step
#print axioms PlanTokenStrengthening.checkedCanonicalDefended_token_step

#check PlanTokenStrengthening.checkedSimulationMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedSimulationMergeDefended_token_step

#check PlanTokenStrengthening.checkedDirectMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedDirectMergeDefended_token_step

#check PlanTokenStrengthening.prepare_preserves_linearity_source
#print axioms PlanTokenStrengthening.prepare_preserves_linearity_source

#check PlanTokenStrengthening.restriction_preserves_linearity_source
#print axioms PlanTokenStrengthening.restriction_preserves_linearity_source

#check PlanTokenStrengthening.revoke_preserves_linearity_source
#print axioms PlanTokenStrengthening.revoke_preserves_linearity_source

#check PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed

#check PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed

#check PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token

#check PlanTokenStrengthening.prepare_binding_new_or_preserved
#print axioms PlanTokenStrengthening.prepare_binding_new_or_preserved

#check PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token

#check PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed
#print axioms PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed

#check PlanTokenLinearity.token_positive_trace_projects_actual
#print axioms PlanTokenLinearity.token_positive_trace_projects_actual

#check PlanTokenLinearity.token_positive_trace_version_mono
#print axioms PlanTokenLinearity.token_positive_trace_version_mono

#check PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected
#print axioms PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected

#check PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality
#print axioms PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality

#check TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact
#print axioms TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact

#check TokenWeightedAccounting.PlanEpochSpec.cardinality_partition
#print axioms TokenWeightedAccounting.PlanEpochSpec.cardinality_partition

#check TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible
#print axioms TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible

#check TokenWeightedAccounting.tokenSafe_unifiedProjection
#print axioms TokenWeightedAccounting.tokenSafe_unifiedProjection

#check TokenWeightedAccounting.unifiedProjection_initial_same_epoch
#print axioms TokenWeightedAccounting.unifiedProjection_initial_same_epoch

#check TokenWeightedAccounting.trace_preserves_unifiedProjection
#print axioms TokenWeightedAccounting.trace_preserves_unifiedProjection

#check TokenWeightedAccounting.trace_initial_token_same_epoch
#print axioms TokenWeightedAccounting.trace_initial_token_same_epoch

#check TokenWeightedAccounting.current_witness_matches_spec
#print axioms TokenWeightedAccounting.current_witness_matches_spec

#check TokenWeightedAccounting.binding_witness_matches_spec
#print axioms TokenWeightedAccounting.binding_witness_matches_spec

end AuthorityContinuity
