import AuthorityContinuity.Trace
import AuthorityContinuity.TopologyExamples
import AuthorityContinuity.PlanTokenStrengthening
import AuthorityContinuity.TokenWeightedAccounting
import AuthorityContinuity.ConfigurationCellQuotient
import AuthorityContinuity.CoordinationDecomposition
import AuthorityContinuity.DurablePrefixTransport
import AuthorityContinuity.RedemptionCommitment
import AuthorityContinuity.RedemptionDomainFrontier

/-!
# Frozen theorem audit

Elaboration of this module confirms the complete paper-facing theorem matrix;
the commands below expose every kernel dependency in the audit log.
-/

namespace AuthorityContinuity

#check checkAC_sound
#print axioms checkAC_sound

#check guardClosure_iff
#print axioms guardClosure_iff

#check simulation_preserves_ac
#print axioms simulation_preserves_ac

#check restriction_preserves_wf_ac
#print axioms restriction_preserves_wf_ac

#check prepare_preserves_wf_ac
#print axioms prepare_preserves_wf_ac

#check ticket_step_preserves_wf_ac
#print axioms ticket_step_preserves_wf_ac

#check LifecycleState.restrictLifecycle_epoch_exact
#print axioms LifecycleState.restrictLifecycle_epoch_exact

#check canonicalProjection_zero
#print axioms canonicalProjection_zero

#check canonicalProjection_mono
#print axioms canonicalProjection_mono

#check Transfer.checkTransfer_sound
#print axioms Transfer.checkTransfer_sound

#check Transfer.topology_fiber_conservation
#print axioms Transfer.topology_fiber_conservation

#check choiceFork_allowed_iff
#print axioms choiceFork_allowed_iff

#check parallelFork_allowed_iff
#print axioms parallelFork_allowed_iff

#check replaceRestore_allowed_iff
#print axioms replaceRestore_allowed_iff

#check liveRestore_allowed_iff
#print axioms liveRestore_allowed_iff

#check choiceFork_preserves_wf_ac
#print axioms choiceFork_preserves_wf_ac

#check parallelFork_preserves_wf_ac
#print axioms parallelFork_preserves_wf_ac

#check replaceRestore_preserves_wf_ac
#print axioms replaceRestore_preserves_wf_ac

#check liveRestore_preserves_wf_ac
#print axioms liveRestore_preserves_wf_ac

#check MergeCheck.checkMergeStructure_sound
#print axioms MergeCheck.checkMergeStructure_sound

#check simulation_merge_preserves_wf_ac
#print axioms simulation_merge_preserves_wf_ac

#check direct_merge_preserves_wf_ac
#print axioms direct_merge_preserves_wf_ac

#check step_preserves_wf_ac
#print axioms step_preserves_wf_ac

#check step_attempt_safe
#print axioms step_attempt_safe

#check step_preserves_existing_binding
#print axioms step_preserves_existing_binding

#check trace_preserves_existing_binding
#print axioms trace_preserves_existing_binding

#check trace_preserves_wf_ac
#print axioms trace_preserves_wf_ac

#check trace_terminal_mono
#print axioms trace_terminal_mono

#check trace_epoch_mono
#print axioms trace_epoch_mono

#check SimulatedTrace.attempt_binding_final
#print axioms SimulatedTrace.attempt_binding_final

#check effect_coverage
#print axioms effect_coverage

#check concrete_trace_authority_safety
#print axioms concrete_trace_authority_safety

#check TopologyExamples.fresh_fragment_parallel_preflight
#print axioms TopologyExamples.fresh_fragment_parallel_preflight

/-! Source-derived token transport and within-plan-epoch accounting. -/

#check PlanTokenLinearity.TokenState.checkLinear_sound
#print axioms PlanTokenLinearity.TokenState.checkLinear_sound

#check PlanTokenLinearity.TokenState.LinearValid.token_trichotomy
#print axioms PlanTokenLinearity.TokenState.LinearValid.token_trichotomy

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete

#check PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.bound_durable_origin_afterTransfer
#print axioms PlanTokenStrengthening.bound_durable_origin_afterTransfer

#check PlanTokenStrengthening.afterTransfer_preserves_linearity_source
#print axioms PlanTokenStrengthening.afterTransfer_preserves_linearity_source

#check PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkedCanonicalDefended_token_step
#print axioms PlanTokenStrengthening.checkedCanonicalDefended_token_step

#check PlanTokenStrengthening.checkedSimulationMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedSimulationMergeDefended_token_step

#check PlanTokenStrengthening.checkedDirectMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedDirectMergeDefended_token_step

#check PlanTokenStrengthening.prepare_preserves_linearity_source
#print axioms PlanTokenStrengthening.prepare_preserves_linearity_source

#check PlanTokenStrengthening.restriction_preserves_linearity_source
#print axioms PlanTokenStrengthening.restriction_preserves_linearity_source

#check PlanTokenStrengthening.revoke_preserves_linearity_source
#print axioms PlanTokenStrengthening.revoke_preserves_linearity_source

#check PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed

#check PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed

#check PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token

#check PlanTokenStrengthening.prepare_binding_new_or_preserved
#print axioms PlanTokenStrengthening.prepare_binding_new_or_preserved

#check PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token

#check PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed
#print axioms PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed

#check PlanTokenLinearity.token_positive_trace_projects_actual
#print axioms PlanTokenLinearity.token_positive_trace_projects_actual

#check PlanTokenLinearity.token_positive_trace_version_mono
#print axioms PlanTokenLinearity.token_positive_trace_version_mono

#check PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected
#print axioms PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected

#check PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality
#print axioms PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality

#check TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact
#print axioms TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact

#check TokenWeightedAccounting.PlanEpochSpec.cardinality_partition
#print axioms TokenWeightedAccounting.PlanEpochSpec.cardinality_partition

#check TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible
#print axioms TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible

#check TokenWeightedAccounting.tokenSafe_unifiedProjection
#print axioms TokenWeightedAccounting.tokenSafe_unifiedProjection

#check TokenWeightedAccounting.unifiedProjection_initial_same_epoch
#print axioms TokenWeightedAccounting.unifiedProjection_initial_same_epoch

#check TokenWeightedAccounting.trace_preserves_unifiedProjection
#print axioms TokenWeightedAccounting.trace_preserves_unifiedProjection

#check TokenWeightedAccounting.trace_initial_token_same_epoch
#print axioms TokenWeightedAccounting.trace_initial_token_same_epoch

#check TokenWeightedAccounting.current_witness_matches_spec
#print axioms TokenWeightedAccounting.current_witness_matches_spec

#check TokenWeightedAccounting.binding_witness_matches_spec
#print axioms TokenWeightedAccounting.binding_witness_matches_spec

/-! Classical configuration-morphism bridge and strict cell fixtures. -/

#check ConfigurationCellQuotient.collision_capacity_one_witness
#print axioms ConfigurationCellQuotient.collision_capacity_one_witness

#check ConfigurationCellQuotient.forbidden_image_indicator_witness
#print axioms ConfigurationCellQuotient.forbidden_image_indicator_witness

#check ConfigurationCellQuotient.universalAdditiveTransport_iff_configMorphism
#print axioms ConfigurationCellQuotient.universalAdditiveTransport_iff_configMorphism

#check ConfigurationCellQuotient.Fixtures.two_handles_one_cell
#print axioms ConfigurationCellQuotient.Fixtures.two_handles_one_cell

#check ConfigurationCellQuotient.Fixtures.exclusive_shared_lineage_transports
#print axioms ConfigurationCellQuotient.Fixtures.exclusive_shared_lineage_transports

#check ConfigurationCellQuotient.Fixtures.parallel_capacity_one_counterexample
#print axioms ConfigurationCellQuotient.Fixtures.parallel_capacity_one_counterexample

/-! Exact coordination factorization over future configuration families. -/

#check CoordinationDecomposition.cut_minimalNonface_witness
#print axioms CoordinationDecomposition.cut_minimalNonface_witness

#check CoordinationDecomposition.exactFactorization_iff_minimalNonfaces_withinBlocks
#print axioms CoordinationDecomposition.exactFactorization_iff_minimalNonfaces_withinBlocks

#check CoordinationDecomposition.exactFactorization_iff_constant_on_mustCoordinate
#print axioms CoordinationDecomposition.exactFactorization_iff_constant_on_mustCoordinate

#check CoordinationDecomposition.cut_minimalNonface_additive_witness
#print axioms CoordinationDecomposition.cut_minimalNonface_additive_witness

#check CoordinationDecomposition.Fixtures.every_pair_allowed
#print axioms CoordinationDecomposition.Fixtures.every_pair_allowed

#check CoordinationDecomposition.Fixtures.splitBlock_admits_forbidden_triple
#print axioms CoordinationDecomposition.Fixtures.splitBlock_admits_forbidden_triple

#check CoordinationDecomposition.Fixtures.rankTwoFamily_not_exactly_factorized
#print axioms CoordinationDecomposition.Fixtures.rankTwoFamily_not_exactly_factorized

#check CoordinationDecomposition.Fixtures.rankTwoFamily_additive_counterexample
#print axioms CoordinationDecomposition.Fixtures.rankTwoFamily_additive_counterexample

/-! Durable-prefix transport and greatest safe future synthesis. -/

#check DurablePrefixTransport.universalPrefixTransport_iff_prefixConfigMorphism
#print axioms DurablePrefixTransport.universalPrefixTransport_iff_prefixConfigMorphism

#check DurablePrefixTransport.required_subset_safeFuture_iff_exists_admitted
#print axioms DurablePrefixTransport.required_subset_safeFuture_iff_exists_admitted

#check DurablePrefixTransport.safeFuture_wellFormed
#print axioms DurablePrefixTransport.safeFuture_wellFormed

#check DurablePrefixTransport.safeFuture_exactFactorization_iff_mustCoordinate
#print axioms DurablePrefixTransport.safeFuture_exactFactorization_iff_mustCoordinate

#check DurablePrefixTransport.committedAtoms_mono_of_ledgerMonotone
#print axioms DurablePrefixTransport.committedAtoms_mono_of_ledgerMonotone

#check DurablePrefixTransport.durable_atom_in_future_forbids_universal_reuse
#print axioms DurablePrefixTransport.durable_atom_in_future_forbids_universal_reuse

#check DurablePrefixTransport.Fixtures.snapshot_only_restored_future_transports
#print axioms DurablePrefixTransport.Fixtures.snapshot_only_restored_future_transports

#check DurablePrefixTransport.Fixtures.durable_receipt_blocks_restored_future
#print axioms DurablePrefixTransport.Fixtures.durable_receipt_blocks_restored_future

#check DurablePrefixTransport.Fixtures.distinct_atom_future_remains_transportable
#print axioms DurablePrefixTransport.Fixtures.distinct_atom_future_remains_transportable

/-! Operational commitment core; topology-changing operators are separate. -/

#check RedemptionCommitment.fresh_preserves_safe
#print axioms RedemptionCommitment.fresh_preserves_safe

#check RedemptionCommitment.step_preserves_phaseWF
#print axioms RedemptionCommitment.step_preserves_phaseWF

#check RedemptionCommitment.step_phase_mono
#print axioms RedemptionCommitment.step_phase_mono

#check RedemptionCommitment.rtc_preserves_safe
#print axioms RedemptionCommitment.rtc_preserves_safe

#check RedemptionCommitment.rtc_preserves_phaseWF
#print axioms RedemptionCommitment.rtc_preserves_phaseWF

#check RedemptionCommitment.rtc_phase_mono
#print axioms RedemptionCommitment.rtc_phase_mono

#check RedemptionCommitment.rtc_ledger_mono
#print axioms RedemptionCommitment.rtc_ledger_mono

#check RedemptionCommitment.committed_card_le_issued_card
#print axioms RedemptionCommitment.committed_card_le_issued_card

#check RedemptionCommitment.step_committed_card
#print axioms RedemptionCommitment.step_committed_card

#check RedemptionCommitment.Trace.committed_card_growth
#print axioms RedemptionCommitment.Trace.committed_card_growth

#check RedemptionCommitment.conflicting_digest_has_no_retry
#print axioms RedemptionCommitment.conflicting_digest_has_no_retry

#check RedemptionCommitment.Fixtures.three_retries_trace
#print axioms RedemptionCommitment.Fixtures.three_retries_trace

#check RedemptionCommitment.Fixtures.cloned_private_cells_two_commitments
#print axioms RedemptionCommitment.Fixtures.cloned_private_cells_two_commitments

#check RedemptionCommitment.Fixtures.rollback_local_restore_yields_two_receipts
#print axioms RedemptionCommitment.Fixtures.rollback_local_restore_yields_two_receipts

/-! Operational and fixed-horizon redemption-domain frontier. -/

#check RedemptionDomainFrontier.ResponseIdentity.retry_successes_share_one_commitment
#print axioms RedemptionDomainFrontier.ResponseIdentity.retry_successes_share_one_commitment

#check RedemptionDomainFrontier.ResponseIdentity.same_operation_two_cells_create_two_commitments
#print axioms RedemptionDomainFrontier.ResponseIdentity.same_operation_two_cells_create_two_commitments

#check RedemptionDomainFrontier.OneShotRun.spent_mono
#print axioms RedemptionDomainFrontier.OneShotRun.spent_mono

#check RedemptionDomainFrontier.OneShotRun.final_card_eq_initial_add_commitment_length
#print axioms RedemptionDomainFrontier.OneShotRun.final_card_eq_initial_add_commitment_length

#check RedemptionDomainFrontier.OneShotRun.initial_card_add_commitment_length_le_reachable_card
#print axioms RedemptionDomainFrontier.OneShotRun.initial_card_add_commitment_length_le_reachable_card

#check RedemptionDomainFrontier.admissible_card_le_unusedActiveCells_card
#print axioms RedemptionDomainFrontier.admissible_card_le_unusedActiveCells_card

#check RedemptionDomainFrontier.committed_add_accepted_card_le_reachableCells_card
#print axioms RedemptionDomainFrontier.committed_add_accepted_card_le_reachableCells_card

#check RedemptionDomainFrontier.exists_tight_admissible_of_soloAvailable_productIndependent
#print axioms RedemptionDomainFrontier.exists_tight_admissible_of_soloAvailable_productIndependent

#check RedemptionDomainFrontier.all_admissible_card_le_iff_unusedActiveCells_card_le_of_independent
#print axioms RedemptionDomainFrontier.all_admissible_card_le_iff_unusedActiveCells_card_le_of_independent

#check RedemptionDomainFrontier.unusedActiveCells_card_eq_activeOccurrences_card_of_independent
#print axioms RedemptionDomainFrontier.unusedActiveCells_card_eq_activeOccurrences_card_of_independent

#check RedemptionDomainFrontier.independentOccurrences_single_redemption_iff_current_card_le_one
#print axioms RedemptionDomainFrontier.independentOccurrences_single_redemption_iff_current_card_le_one

#check RedemptionDomainFrontier.SharedCellAliases.shared_cell_aliases_safe_but_not_occurrence_linear
#print axioms RedemptionDomainFrontier.SharedCellAliases.shared_cell_aliases_safe_but_not_occurrence_linear

#check RedemptionDomainFrontier.DurableConsumedHistory.restored_attempt_blocked_by_pruned_consumed_history
#print axioms RedemptionDomainFrontier.DurableConsumedHistory.restored_attempt_blocked_by_pruned_consumed_history

#check RedemptionDomainFrontier.ExclusiveChoice.two_cells_but_choice_accepts_at_most_one
#print axioms RedemptionDomainFrontier.ExclusiveChoice.two_cells_but_choice_accepts_at_most_one

#check RedemptionDomainFrontier.ExclusiveChoice.choice_is_not_productIndependent
#print axioms RedemptionDomainFrontier.ExclusiveChoice.choice_is_not_productIndependent

#check RedemptionDomainFrontier.RollbackClonedCells.rollback_clone_double_accept_counterexample
#print axioms RedemptionDomainFrontier.RollbackClonedCells.rollback_clone_double_accept_counterexample

end AuthorityContinuity
