import AuthorityContinuity.Trace
import AuthorityContinuity.TopologyExamples
import AuthorityContinuity.PlanTokenStrengthening
import AuthorityContinuity.TokenWeightedAccounting
import AuthorityContinuity.ConfigurationCellQuotient
import AuthorityContinuity.CoordinationDecomposition
import AuthorityContinuity.DurablePrefixTransport
import AuthorityContinuity.TypedHistoryAdmission
import AuthorityContinuity.ControllerCoverAdmission
import AuthorityContinuity.IdentityQuotientSeparation
import AuthorityContinuity.RedemptionCommitment
import AuthorityContinuity.RedemptionDomainFrontier

/-!
# Frozen theorem audit

Elaboration of this module confirms the complete paper-facing theorem matrix;
the commands below expose every kernel dependency in the audit log.
-/

namespace AuthorityContinuity

#check checkAC_sound
#print axioms checkAC_sound

#check guardClosure_iff
#print axioms guardClosure_iff

#check simulation_preserves_ac
#print axioms simulation_preserves_ac

#check restriction_preserves_wf_ac
#print axioms restriction_preserves_wf_ac

#check prepare_preserves_wf_ac
#print axioms prepare_preserves_wf_ac

#check ticket_step_preserves_wf_ac
#print axioms ticket_step_preserves_wf_ac

#check LifecycleState.restrictLifecycle_epoch_exact
#print axioms LifecycleState.restrictLifecycle_epoch_exact

#check canonicalProjection_zero
#print axioms canonicalProjection_zero

#check canonicalProjection_mono
#print axioms canonicalProjection_mono

#check Transfer.checkTransfer_sound
#print axioms Transfer.checkTransfer_sound

#check Transfer.topology_fiber_conservation
#print axioms Transfer.topology_fiber_conservation

#check choiceFork_allowed_iff
#print axioms choiceFork_allowed_iff

#check parallelFork_allowed_iff
#print axioms parallelFork_allowed_iff

#check replaceRestore_allowed_iff
#print axioms replaceRestore_allowed_iff

#check liveRestore_allowed_iff
#print axioms liveRestore_allowed_iff

#check choiceFork_preserves_wf_ac
#print axioms choiceFork_preserves_wf_ac

#check parallelFork_preserves_wf_ac
#print axioms parallelFork_preserves_wf_ac

#check replaceRestore_preserves_wf_ac
#print axioms replaceRestore_preserves_wf_ac

#check liveRestore_preserves_wf_ac
#print axioms liveRestore_preserves_wf_ac

#check MergeCheck.checkMergeStructure_sound
#print axioms MergeCheck.checkMergeStructure_sound

#check simulation_merge_preserves_wf_ac
#print axioms simulation_merge_preserves_wf_ac

#check direct_merge_preserves_wf_ac
#print axioms direct_merge_preserves_wf_ac

#check step_preserves_wf_ac
#print axioms step_preserves_wf_ac

#check step_attempt_safe
#print axioms step_attempt_safe

#check step_preserves_existing_binding
#print axioms step_preserves_existing_binding

#check trace_preserves_existing_binding
#print axioms trace_preserves_existing_binding

#check trace_preserves_wf_ac
#print axioms trace_preserves_wf_ac

#check trace_terminal_mono
#print axioms trace_terminal_mono

#check trace_epoch_mono
#print axioms trace_epoch_mono

#check SimulatedTrace.attempt_binding_final
#print axioms SimulatedTrace.attempt_binding_final

#check effect_coverage
#print axioms effect_coverage

#check concrete_trace_authority_safety
#print axioms concrete_trace_authority_safety

#check TopologyExamples.fresh_fragment_parallel_preflight
#print axioms TopologyExamples.fresh_fragment_parallel_preflight

/-! Source-derived token transport and within-plan-epoch accounting. -/

#check PlanTokenLinearity.TokenState.checkLinear_sound
#print axioms PlanTokenLinearity.TokenState.checkLinear_sound

#check PlanTokenLinearity.TokenState.LinearValid.token_trichotomy
#print axioms PlanTokenLinearity.TokenState.LinearValid.token_trichotomy

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_sound

#check PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete
#print axioms PlanTokenStrengthening.checkTransferTokenNonAmplifying_complete

#check PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.afterTransfer_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.canonical_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.simulationMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear
#print axioms PlanTokenStrengthening.directMerge_nonAmplifying_iff_target_current_linear

#check PlanTokenStrengthening.bound_durable_origin_afterTransfer
#print axioms PlanTokenStrengthening.bound_durable_origin_afterTransfer

#check PlanTokenStrengthening.afterTransfer_preserves_linearity_source
#print axioms PlanTokenStrengthening.afterTransfer_preserves_linearity_source

#check PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkCanonicalTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkSimulationMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan
#print axioms PlanTokenStrengthening.checkDirectMergeTokenDefended_eq_tokenPlan

#check PlanTokenStrengthening.checkedCanonicalDefended_token_step
#print axioms PlanTokenStrengthening.checkedCanonicalDefended_token_step

#check PlanTokenStrengthening.checkedSimulationMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedSimulationMergeDefended_token_step

#check PlanTokenStrengthening.checkedDirectMergeDefended_token_step
#print axioms PlanTokenStrengthening.checkedDirectMergeDefended_token_step

#check PlanTokenStrengthening.prepare_preserves_linearity_source
#print axioms PlanTokenStrengthening.prepare_preserves_linearity_source

#check PlanTokenStrengthening.restriction_preserves_linearity_source
#print axioms PlanTokenStrengthening.restriction_preserves_linearity_source

#check PlanTokenStrengthening.revoke_preserves_linearity_source
#print axioms PlanTokenStrengthening.revoke_preserves_linearity_source

#check PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_linearity_source_decomposed

#check PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_source_decomposed

#check PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.tokenPositiveStep_preserves_existing_operation_token

#check PlanTokenStrengthening.prepare_binding_new_or_preserved
#print axioms PlanTokenStrengthening.prepare_binding_new_or_preserved

#check PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token
#print axioms PlanTokenStrengthening.token_positive_trace_preserves_existing_operation_token

#check PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed
#print axioms PlanTokenStrengthening.within_plan_epoch_initial_tokens_fixed

#check PlanTokenLinearity.token_positive_trace_projects_actual
#print axioms PlanTokenLinearity.token_positive_trace_projects_actual

#check PlanTokenLinearity.token_positive_trace_version_mono
#print axioms PlanTokenLinearity.token_positive_trace_version_mono

#check PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected
#print axioms PlanTokenLinearity.ZeroDemandRegression.zero_demand_parallelFork_rejected

#check PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality
#print axioms PlanTokenLinearity.ZeroDemandRegression.duplicated_token_fiber_cardinality

#check TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact
#print axioms TokenWeightedAccounting.PlanEpochSpec.weighted_partition_exact

#check TokenWeightedAccounting.PlanEpochSpec.cardinality_partition
#print axioms TokenWeightedAccounting.PlanEpochSpec.cardinality_partition

#check TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible
#print axioms TokenWeightedAccounting.PlanEpochSpec.zero_weight_token_visible

#check TokenWeightedAccounting.tokenSafe_unifiedProjection
#print axioms TokenWeightedAccounting.tokenSafe_unifiedProjection

#check TokenWeightedAccounting.unifiedProjection_initial_same_epoch
#print axioms TokenWeightedAccounting.unifiedProjection_initial_same_epoch

#check TokenWeightedAccounting.trace_preserves_unifiedProjection
#print axioms TokenWeightedAccounting.trace_preserves_unifiedProjection

#check TokenWeightedAccounting.trace_initial_token_same_epoch
#print axioms TokenWeightedAccounting.trace_initial_token_same_epoch

#check TokenWeightedAccounting.current_witness_matches_spec
#print axioms TokenWeightedAccounting.current_witness_matches_spec

#check TokenWeightedAccounting.binding_witness_matches_spec
#print axioms TokenWeightedAccounting.binding_witness_matches_spec

/-! Classical configuration-morphism bridge and strict cell fixtures. -/

#check ConfigurationCellQuotient.collision_capacity_one_witness
#print axioms ConfigurationCellQuotient.collision_capacity_one_witness

#check ConfigurationCellQuotient.forbidden_image_indicator_witness
#print axioms ConfigurationCellQuotient.forbidden_image_indicator_witness

#check ConfigurationCellQuotient.universalAdditiveTransport_iff_configMorphism
#print axioms ConfigurationCellQuotient.universalAdditiveTransport_iff_configMorphism

#check ConfigurationCellQuotient.Fixtures.two_handles_one_cell
#print axioms ConfigurationCellQuotient.Fixtures.two_handles_one_cell

#check ConfigurationCellQuotient.Fixtures.exclusive_shared_lineage_transports
#print axioms ConfigurationCellQuotient.Fixtures.exclusive_shared_lineage_transports

#check ConfigurationCellQuotient.Fixtures.parallel_capacity_one_counterexample
#print axioms ConfigurationCellQuotient.Fixtures.parallel_capacity_one_counterexample

/-! Exact coordination factorization over future configuration families. -/

#check CoordinationDecomposition.cut_minimalNonface_witness
#print axioms CoordinationDecomposition.cut_minimalNonface_witness

#check CoordinationDecomposition.exactFactorization_iff_minimalNonfaces_withinBlocks
#print axioms CoordinationDecomposition.exactFactorization_iff_minimalNonfaces_withinBlocks

#check CoordinationDecomposition.exactFactorization_iff_constant_on_mustCoordinate
#print axioms CoordinationDecomposition.exactFactorization_iff_constant_on_mustCoordinate

#check CoordinationDecomposition.cut_minimalNonface_additive_witness
#print axioms CoordinationDecomposition.cut_minimalNonface_additive_witness

#check CoordinationDecomposition.Fixtures.every_pair_allowed
#print axioms CoordinationDecomposition.Fixtures.every_pair_allowed

#check CoordinationDecomposition.Fixtures.splitBlock_admits_forbidden_triple
#print axioms CoordinationDecomposition.Fixtures.splitBlock_admits_forbidden_triple

#check CoordinationDecomposition.Fixtures.rankTwoFamily_not_exactly_factorized
#print axioms CoordinationDecomposition.Fixtures.rankTwoFamily_not_exactly_factorized

#check CoordinationDecomposition.Fixtures.rankTwoFamily_additive_counterexample
#print axioms CoordinationDecomposition.Fixtures.rankTwoFamily_additive_counterexample

/-! Durable-prefix transport and greatest safe future synthesis. -/

#check DurablePrefixTransport.universalPrefixTransport_iff_prefixConfigMorphism
#print axioms DurablePrefixTransport.universalPrefixTransport_iff_prefixConfigMorphism

#check DurablePrefixTransport.required_subset_safeFuture_iff_exists_admitted
#print axioms DurablePrefixTransport.required_subset_safeFuture_iff_exists_admitted

#check DurablePrefixTransport.safeFuture_wellFormed
#print axioms DurablePrefixTransport.safeFuture_wellFormed

#check DurablePrefixTransport.safeFuture_exactFactorization_iff_mustCoordinate
#print axioms DurablePrefixTransport.safeFuture_exactFactorization_iff_mustCoordinate

#check DurablePrefixTransport.committedAtoms_mono_of_ledgerMonotone
#print axioms DurablePrefixTransport.committedAtoms_mono_of_ledgerMonotone

#check DurablePrefixTransport.durable_atom_in_future_forbids_universal_reuse
#print axioms DurablePrefixTransport.durable_atom_in_future_forbids_universal_reuse

#check DurablePrefixTransport.Fixtures.snapshot_only_restored_future_transports
#print axioms DurablePrefixTransport.Fixtures.snapshot_only_restored_future_transports

#check DurablePrefixTransport.Fixtures.durable_receipt_blocks_restored_future
#print axioms DurablePrefixTransport.Fixtures.durable_receipt_blocks_restored_future

#check DurablePrefixTransport.Fixtures.distinct_atom_future_remains_transportable
#print axioms DurablePrefixTransport.Fixtures.distinct_atom_future_remains_transportable

/-! Typed history operators and refinement-certified binding transport. -/

#check TypedHistoryAdmission.familyTensor_wellFormed
#print axioms TypedHistoryAdmission.familyTensor_wellFormed

#check TypedHistoryAdmission.HistoryOp.required_subset_candidate
#print axioms TypedHistoryAdmission.HistoryOp.required_subset_candidate

#check TypedHistoryAdmission.configMorphism_comp
#print axioms TypedHistoryAdmission.configMorphism_comp

#check TypedHistoryAdmission.StructuralRefinement.transports_prefixConfigMorphism
#print axioms TypedHistoryAdmission.StructuralRefinement.transports_prefixConfigMorphism

#check TypedHistoryAdmission.StructuralRefinement.trans
#print axioms TypedHistoryAdmission.StructuralRefinement.trans

#check TypedHistoryAdmission.LeaseSurvival.targetLease_valid
#print axioms TypedHistoryAdmission.LeaseSurvival.targetLease_valid

#check TypedHistoryAdmission.LeaseSurvival.targetLease_atom_not_durable
#print axioms TypedHistoryAdmission.LeaseSurvival.targetLease_atom_not_durable

#check TypedHistoryAdmission.op_fullReadmit_iff_candidate_eq_admittedFuture
#print axioms TypedHistoryAdmission.op_fullReadmit_iff_candidate_eq_admittedFuture

#check TypedHistoryAdmission.op_fullReadmit_preserves_required
#print axioms TypedHistoryAdmission.op_fullReadmit_preserves_required

#check TypedHistoryAdmission.op_no_admitted_iff_exists_required_witness
#print axioms TypedHistoryAdmission.op_no_admitted_iff_exists_required_witness

#check TypedHistoryAdmission.op_admission_trichotomy
#print axioms TypedHistoryAdmission.op_admission_trichotomy

#check TypedHistoryAdmission.op_admission_classes_pairwise
#print axioms TypedHistoryAdmission.op_admission_classes_pairwise

#check TypedHistoryAdmission.classifyAdmission_sound
#print axioms TypedHistoryAdmission.classifyAdmission_sound

#check TypedHistoryAdmission.op_admittedFuture_exactFactorization_iff_mustCoordinate
#print axioms TypedHistoryAdmission.op_admittedFuture_exactFactorization_iff_mustCoordinate

#check TypedHistoryAdmission.Fixtures.choice_certificate_inherits
#print axioms TypedHistoryAdmission.Fixtures.choice_certificate_inherits

#check TypedHistoryAdmission.Fixtures.parallel_has_no_structural_refinement
#print axioms TypedHistoryAdmission.Fixtures.parallel_has_no_structural_refinement

#check TypedHistoryAdmission.Fixtures.SharedLease.alternatives_share_surviving_lease
#print axioms TypedHistoryAdmission.Fixtures.SharedLease.alternatives_share_surviving_lease

#check TypedHistoryAdmission.Fixtures.SharedLease.choice_split_controllers_not_exact
#print axioms TypedHistoryAdmission.Fixtures.SharedLease.choice_split_controllers_not_exact

#check TypedHistoryAdmission.Fixtures.SharedLease.choice_shared_controller_exact
#print axioms TypedHistoryAdmission.Fixtures.SharedLease.choice_shared_controller_exact

#check TypedHistoryAdmission.Fixtures.SharedLease.parallel_has_no_shared_lease_refinement
#print axioms TypedHistoryAdmission.Fixtures.SharedLease.parallel_has_no_shared_lease_refinement

#check TypedHistoryAdmission.Fixtures.SharedLease.parallel_shared_lease_has_no_pruning_repair
#print axioms TypedHistoryAdmission.Fixtures.SharedLease.parallel_shared_lease_has_no_pruning_repair

/-! Relational controller covers and manifest-relative deployment readiness. -/

#check ControllerCoverAdmission.rawPhysicalCoverProduct_mono_coLive
#print axioms ControllerCoverAdmission.rawPhysicalCoverProduct_mono_coLive

#check ControllerCoverAdmission.safeGroup_of_subset
#print axioms ControllerCoverAdmission.safeGroup_of_subset

#check ControllerCoverAdmission.hereditarySafeCoLiveRestriction_subset
#print axioms ControllerCoverAdmission.hereditarySafeCoLiveRestriction_subset

#check ControllerCoverAdmission.hereditarySafeCoLiveRestriction_downwardClosed
#print axioms ControllerCoverAdmission.hereditarySafeCoLiveRestriction_downwardClosed

#check ControllerCoverAdmission.hereditarySafeCoLiveRestriction_rawPhysical_safe
#print axioms ControllerCoverAdmission.hereditarySafeCoLiveRestriction_rawPhysical_safe

#check ControllerCoverAdmission.hereditarySafeCoLiveRestriction_greatest
#print axioms ControllerCoverAdmission.hereditarySafeCoLiveRestriction_greatest

#check ControllerCoverAdmission.required_subset_hereditarySafeCoLiveRestriction_iff_exists_deploymentReady
#print axioms ControllerCoverAdmission.required_subset_hereditarySafeCoLiveRestriction_iff_exists_deploymentReady

#check ControllerCoverAdmission.prefixThenControllerRepair_rawPhysical_safe
#print axioms ControllerCoverAdmission.prefixThenControllerRepair_rawPhysical_safe

#check ControllerCoverAdmission.prefixThenControllerRepair_greatest
#print axioms ControllerCoverAdmission.prefixThenControllerRepair_greatest

#check ControllerCoverAdmission.not_deploymentReady_iff_overpermission_or_missingRequired
#print axioms ControllerCoverAdmission.not_deploymentReady_iff_overpermission_or_missingRequired

#check ControllerCoverAdmission.actual_prefixConfigMorphism_of_deploymentReady
#print axioms ControllerCoverAdmission.actual_prefixConfigMorphism_of_deploymentReady

#check ControllerCoverAdmission.functionalPartition_deploymentReady_iff_mustCoordinate
#print axioms ControllerCoverAdmission.functionalPartition_deploymentReady_iff_mustCoordinate

#check ControllerCoverAdmission.rawPhysical_partition_eq_localProduct
#print axioms ControllerCoverAdmission.rawPhysical_partition_eq_localProduct
#check ControllerCoverAdmission.partitionCoLive_downwardClosed
#print axioms ControllerCoverAdmission.partitionCoLive_downwardClosed

#check IdentityQuotientSeparation.Fixtures.identityQuotient_worlds_wellStructured
#print axioms IdentityQuotientSeparation.Fixtures.identityQuotient_worlds_wellStructured

#check IdentityQuotientSeparation.Fixtures.identityQuotients_independently_necessary
#print axioms IdentityQuotientSeparation.Fixtures.identityQuotients_independently_necessary

#check ControllerCoverAdmission.canonicalPartition_deploymentReady_iff_mustCoordinate
#print axioms ControllerCoverAdmission.canonicalPartition_deploymentReady_iff_mustCoordinate

#check ControllerCoverAdmission.forbidden_valid_cover_cases
#print axioms ControllerCoverAdmission.forbidden_valid_cover_cases

#check ControllerCoverAdmission.rawPhysical_subset_admitted_iff_avoids_obstructions
#print axioms ControllerCoverAdmission.rawPhysical_subset_admitted_iff_avoids_obstructions

#check ControllerCoverAdmission.deploymentReady_iff_required_coverage_and_avoids_obstructions
#print axioms ControllerCoverAdmission.deploymentReady_iff_required_coverage_and_avoids_obstructions

#check ControllerCoverAdmission.physical_overpermission_has_correlationCutWitness
#print axioms ControllerCoverAdmission.physical_overpermission_has_correlationCutWitness

#check ControllerCoverAdmission.correlationCut_uses_distinct_contributing_controllers
#print axioms ControllerCoverAdmission.correlationCut_uses_distinct_contributing_controllers

#check ControllerCoverAdmission.Fixtures.split_controllers_admit_forbidden_triple
#print axioms ControllerCoverAdmission.Fixtures.split_controllers_admit_forbidden_triple

#check ControllerCoverAdmission.no_exact_checker_of_observation_collision
#print axioms ControllerCoverAdmission.no_exact_checker_of_observation_collision

#check ControllerCoverAdmission.rawPhysicalCoverProduct_has_card_bounded_plan
#print axioms ControllerCoverAdmission.rawPhysicalCoverProduct_has_card_bounded_plan

#check ControllerCoverAdmission.contractObservationArity_is_bound
#print axioms ControllerCoverAdmission.contractObservationArity_is_bound

#check ControllerCoverAdmission.deploymentReady_iff_of_contract_observation
#print axioms ControllerCoverAdmission.deploymentReady_iff_of_contract_observation

#check ControllerCoverAdmission.deploymentReady_iff_of_contractObservationArity_projection_eq
#print axioms ControllerCoverAdmission.deploymentReady_iff_of_contractObservationArity_projection_eq

#check ControllerCoverAdmission.coLiveProjection_downwardClosed
#print axioms ControllerCoverAdmission.coLiveProjection_downwardClosed

#check ControllerCoverAdmission.coLiveProjection_idempotent
#print axioms ControllerCoverAdmission.coLiveProjection_idempotent

#check ControllerCoverAdmission.deploymentReady_iff_contractProjection
#print axioms ControllerCoverAdmission.deploymentReady_iff_contractProjection

#check ControllerCoverAdmission.deploymentReady_iff_of_attested_exact_projection
#print axioms ControllerCoverAdmission.deploymentReady_iff_of_attested_exact_projection

#check ControllerCoverAdmission.Fixtures.pairwise_realization_ready
#print axioms ControllerCoverAdmission.Fixtures.pairwise_realization_ready

#check ControllerCoverAdmission.Fixtures.pairwise_raw_eq_rankTwo
#print axioms ControllerCoverAdmission.Fixtures.pairwise_raw_eq_rankTwo

#check ControllerCoverAdmission.Fixtures.triple_realization_not_ready
#print axioms ControllerCoverAdmission.Fixtures.triple_realization_not_ready

#check ControllerCoverAdmission.Fixtures.triple_realization_correlationCutWitness
#print axioms ControllerCoverAdmission.Fixtures.triple_realization_correlationCutWitness

#check ControllerCoverAdmission.Fixtures.pairwiseCoLive3_downwardClosed
#print axioms ControllerCoverAdmission.Fixtures.pairwiseCoLive3_downwardClosed

#check ControllerCoverAdmission.Fixtures.tripleCoLive3_downwardClosed
#print axioms ControllerCoverAdmission.Fixtures.tripleCoLive3_downwardClosed

#check ControllerCoverAdmission.Fixtures.pairwise_projection_collision
#print axioms ControllerCoverAdmission.Fixtures.pairwise_projection_collision

#check ControllerCoverAdmission.Fixtures.no_pairwise_observation_checker_exact
#print axioms ControllerCoverAdmission.Fixtures.no_pairwise_observation_checker_exact

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.bounded_realization_ready
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.bounded_realization_ready

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.full_realization_not_ready
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.full_realization_not_ready

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.full_configuration_minimalNonface
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.full_configuration_minimalNonface

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.full_configuration_correlationCutWitness
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.full_configuration_correlationCutWitness

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.contractObservationArity_rankFamily
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.contractObservationArity_rankFamily

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.projection_collision
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.projection_collision

#check ControllerCoverAdmission.Fixtures.ArbitraryArity.no_lower_arity_downwardClosed_observation_checker_exact
#print axioms ControllerCoverAdmission.Fixtures.ArbitraryArity.no_lower_arity_downwardClosed_observation_checker_exact

/-! Operational commitment core; topology-changing operators are separate. -/

#check RedemptionCommitment.fresh_preserves_safe
#print axioms RedemptionCommitment.fresh_preserves_safe

#check RedemptionCommitment.step_preserves_phaseWF
#print axioms RedemptionCommitment.step_preserves_phaseWF

#check RedemptionCommitment.step_phase_mono
#print axioms RedemptionCommitment.step_phase_mono

#check RedemptionCommitment.rtc_preserves_safe
#print axioms RedemptionCommitment.rtc_preserves_safe

#check RedemptionCommitment.rtc_preserves_phaseWF
#print axioms RedemptionCommitment.rtc_preserves_phaseWF

#check RedemptionCommitment.rtc_phase_mono
#print axioms RedemptionCommitment.rtc_phase_mono

#check RedemptionCommitment.rtc_ledger_mono
#print axioms RedemptionCommitment.rtc_ledger_mono

#check RedemptionCommitment.committed_card_le_issued_card
#print axioms RedemptionCommitment.committed_card_le_issued_card

#check RedemptionCommitment.step_committed_card
#print axioms RedemptionCommitment.step_committed_card

#check RedemptionCommitment.Trace.committed_card_growth
#print axioms RedemptionCommitment.Trace.committed_card_growth

#check RedemptionCommitment.conflicting_digest_has_no_retry
#print axioms RedemptionCommitment.conflicting_digest_has_no_retry

#check RedemptionCommitment.Fixtures.three_retries_trace
#print axioms RedemptionCommitment.Fixtures.three_retries_trace

#check RedemptionCommitment.Fixtures.cloned_private_cells_two_commitments
#print axioms RedemptionCommitment.Fixtures.cloned_private_cells_two_commitments

#check RedemptionCommitment.Fixtures.rollback_local_restore_yields_two_receipts
#print axioms RedemptionCommitment.Fixtures.rollback_local_restore_yields_two_receipts

/-! Operational and fixed-horizon redemption-domain frontier. -/

#check RedemptionDomainFrontier.ResponseIdentity.retry_successes_share_one_commitment
#print axioms RedemptionDomainFrontier.ResponseIdentity.retry_successes_share_one_commitment

#check RedemptionDomainFrontier.ResponseIdentity.same_operation_two_cells_create_two_commitments
#print axioms RedemptionDomainFrontier.ResponseIdentity.same_operation_two_cells_create_two_commitments

#check RedemptionDomainFrontier.OneShotRun.spent_mono
#print axioms RedemptionDomainFrontier.OneShotRun.spent_mono

#check RedemptionDomainFrontier.OneShotRun.final_card_eq_initial_add_commitment_length
#print axioms RedemptionDomainFrontier.OneShotRun.final_card_eq_initial_add_commitment_length

#check RedemptionDomainFrontier.OneShotRun.initial_card_add_commitment_length_le_reachable_card
#print axioms RedemptionDomainFrontier.OneShotRun.initial_card_add_commitment_length_le_reachable_card

#check RedemptionDomainFrontier.admissible_card_le_unusedActiveCells_card
#print axioms RedemptionDomainFrontier.admissible_card_le_unusedActiveCells_card

#check RedemptionDomainFrontier.committed_add_accepted_card_le_reachableCells_card
#print axioms RedemptionDomainFrontier.committed_add_accepted_card_le_reachableCells_card

#check RedemptionDomainFrontier.exists_tight_admissible_of_soloAvailable_productIndependent
#print axioms RedemptionDomainFrontier.exists_tight_admissible_of_soloAvailable_productIndependent

#check RedemptionDomainFrontier.all_admissible_card_le_iff_unusedActiveCells_card_le_of_independent
#print axioms RedemptionDomainFrontier.all_admissible_card_le_iff_unusedActiveCells_card_le_of_independent

#check RedemptionDomainFrontier.unusedActiveCells_card_eq_activeOccurrences_card_of_independent
#print axioms RedemptionDomainFrontier.unusedActiveCells_card_eq_activeOccurrences_card_of_independent

#check RedemptionDomainFrontier.independentOccurrences_single_redemption_iff_current_card_le_one
#print axioms RedemptionDomainFrontier.independentOccurrences_single_redemption_iff_current_card_le_one

#check RedemptionDomainFrontier.SharedCellAliases.shared_cell_aliases_safe_but_not_occurrence_linear
#print axioms RedemptionDomainFrontier.SharedCellAliases.shared_cell_aliases_safe_but_not_occurrence_linear

#check RedemptionDomainFrontier.DurableConsumedHistory.restored_attempt_blocked_by_pruned_consumed_history
#print axioms RedemptionDomainFrontier.DurableConsumedHistory.restored_attempt_blocked_by_pruned_consumed_history

#check RedemptionDomainFrontier.ExclusiveChoice.two_cells_but_choice_accepts_at_most_one
#print axioms RedemptionDomainFrontier.ExclusiveChoice.two_cells_but_choice_accepts_at_most_one

#check RedemptionDomainFrontier.ExclusiveChoice.choice_is_not_productIndependent
#print axioms RedemptionDomainFrontier.ExclusiveChoice.choice_is_not_productIndependent

#check RedemptionDomainFrontier.RollbackClonedCells.rollback_clone_double_accept_counterexample
#print axioms RedemptionDomainFrontier.RollbackClonedCells.rollback_clone_double_accept_counterexample

end AuthorityContinuity
